# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run tests and collect coverage
      run: npm run lint
      run: npm run test:coverage
    - name: Run build
      run: npm run build
    - name: Upload coverage to Codecov
        uses: ./
        with:
          files: ./coverage/calculator/coverage-final.json,./coverage/index/coverage-final.json
          file: ./coverage/coverage-final.json
          flags: unittest
          name: codecov-1
